<?php

class DBC2 {
//     const HOST = '164.41.67.207';
//     const USER = 'elefante';
//     const PASSWORD = 'tJTzPhShd6O2E';
//     const DB = 'databaseteste';
    
//     const HOST = 'localhost';
//     const USER = 'postgres';
//     const PASSWORD = 'postgres';
//     const DB = 'databaseteste';

		const HOST = 'localhost';
	    const USER = 'postgres';
	    const PASSWORD = 'postgres';
	    const DB = 'redeunbfb';
}
