<?php

class DBC {
//     const HOST = '164.41.67.207';
//     const USER = 'elefante';
//     const PASSWORD = 'tJTzPhShd6O2E';
//     const DB = 'databaseteste';
    
//     const HOST = 'localhost';
//     const USER = 'postgres';
//     const PASSWORD = 'postgres';
//     const DB = 'redeunbfb';

		const HOST = 'postgresql07.redessociaisonline.com';
	    const USER = 'redessociaison7';
	    const PASSWORD = 'gim@is';
	    const DB = 'redessociaison7';
}
